/* Generated by scripts/gen-image-dims.mjs — do not edit by hand.
   Intrinsic pixel dimensions, used to reserve each image's box before it
   loads. Regenerate with: npm run images:dims */
export const IMAGE_DIMS = {
  "a24-hero": [1600, 900],
  "dot-hero": [1600, 900],
  "dot-proof": [1600, 1134],
  "hamsa-hero": [1600, 900],
  "hamsa-proof": [1200, 1600],
  "highradius-hero": [1600, 1066],
  "highradius-proof": [1103, 1400],
  "portrait": [1200, 1500],
  "restroworks-hero": [1600, 1066],
  "restroworks-proof": [1050, 1400],
  "vivi-hero": [1600, 900],
  "zimyo-hero": [1600, 900],
  "zimyo-proof": [1360, 1600]
};

/** width / height, or null if the file isn't in the map */
export function imageRatio(name) {
  const d = IMAGE_DIMS[name];
  return d ? d[0] / d[1] : null;
}
